modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "https://github.com/starfish-studios/infinite-pi/blob/main/LICENSE"

[[mods]]
modId = "infinite_pie"
version = "${version}"
displayName = "Infinite Pie"
authors = "Starfish Studios"
description = '''
A mod adding a single item - Infinite Pie. It is a pie that is infinite. Happy Pi Day!
'''
logoFile = "icon.png"

[[mixins]]
config = "infinite_pie.mixins.json"