modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "https://github.com/starfish-studios/infinite-pi/blob/main/LICENSE"

[[mods]]
modId = "infinite_pie"
version = "${version}"
displayName = "Infinite Pie"
authors = "Starfish Studios"
description = '''
A mod adding a single item - Infinite Pie. It is a pie that is infinite. Happy Pi Day!
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "infinite_pie-common.mixins.json"